name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1

    - name: Run tests
      run: python scripts/test.py
